site_name: JACoW - CAT - PURR
theme: material
repo_name: 'jacow-org/docs-IPAC'
repo_url: 'https://github.com/JACoW-org/docs-PURR'
nav:
  - Introduction: index.md
  - Functionalities:
    - Connection to MEOW: Functionalities/connection.md
    - Status and Settings: Functionalities/statusAndSettings.md
    - Abstract Booklet generation: Functionalities/abstractBooklet.md
    - Papers Check: Functionalities/papersCheck.md
    - Final Proceedings generation: Functionalities/finalProceedings.md
  - General instructions:
    - How to login to the Indico event: General/JACoWlogin.md
    - How to submit an abstract: General/submission.md
    - How to edit your abstracts: General/editing.md
    - How to edit your contributions: General/contributions.md
