site_name: JACoW - CAT - PURR
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: green
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: green
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
repo_name: 'jacow-org/docs-PURR'
repo_url: 'https://github.com/JACoW-org/docs-PURR'
markdown_extensions:
  - admonition
plugins:
  - privacy
  - search
  - open-in-new-tab:
      add_icon: true
nav:
  - Introduction: index.md
  - Functionalities:
    - Connection to MEOW: Functionalities/connection.md
    - Status and Settings: Functionalities/statusAndSettings.md
    - Abstract Booklet generation: Functionalities/abstractBooklet.md
    - Papers Check: Functionalities/papersCheck.md
    - Final Proceedings generation: Functionalities/finalProceedings.md
